### ISSUE TITLE
Link to phone number

### ISSUE THREAD

**Issue by watsoned** [sbmkvp/edgehill#12]
The link to mobile phone numbers goes to whatsapp rather than to contacts, which for phone numbers not linked to a WhatsApp account creates and error message.  Could this be rectified to go to contacts instead?

**Comment by sbmkvp** [comment]
Detecting if a number is linked to whatsapp might be complicated to do from a web app. The solution might be to have two different buttons one for whatsapp and other for calling.

**Comment by watsoned** [comment]
Is it as easy to just have one button for calling or do you have to create the two buttons in order to  be able to distinguish the call button?

**Comment by sbmkvp** [comment]
The link works as intended on android without any changes to our code.
