### ISSUE TITLE
Refresh page

### ISSUE THREAD

**Issue by watsoned** [sbmkvp/edgehill#2]
Change -(happy to pay)

We originally envisaged having a prayer per day, but I actually quite like the fact that it's randomly selected and comes up with a new prayer at each page refresh.

Please could you make the text "refresh page for next prayer point" a link that refreshes the page?

![screenshot_20160704-081033](https://cloud.githubusercontent.com/assets/20271714/16554025/29d40546-41c4-11e6-997e-32884faacc27.png)

**Comment by sbmkvp** [comment]
fixed
