### ISSUE TITLE
Prayer feed

### ISSUE THREAD

**Issue by watsoned** [sbmkvp/edgehill#3]
Change (happy to pay)

I'd like to provide a link to a third party website by inserting a logo (attached) which links to http://www.geero.net/prayermate/

It should go at the bottom of the prayer page and have the text 
"edgehill also has a PrayerMate feed.  Sign up here"

![prayermateweb](https://cloud.githubusercontent.com/assets/20271714/16554193/1b296f3a-41c5-11e6-9010-537bc1790791.jpg)

**Comment by sbmkvp** [comment]
fixed
